import { Test, TestingModule } from '@nestjs/testing';
import { AuthService } from './auth.service';
import * as bcrypt from 'bcrypt';
import { PrismaService } from 'src/prisma/prisma.service';
import { JwtService } from '@nestjs/jwt';
import { ConfigService } from '@nestjs/config';
import { ConflictException, UnauthorizedException } from '@nestjs/common';
import { CreateAuthDto } from './dto/create-auth.dto';
import { LoginAuthDto } from './dto/login-auth.dto';
import { UserRole, UserStatus } from 'generated/prisma/enums';

// Mock bcrypt at the module level
jest.mock('bcrypt');

describe('AuthService - Unit Tests', () => {
  let service: AuthService;

  //=======================MOCK OBJECTS======================
  // Create a mock PrismaService
  const mockPrismaService = {
    user: {
      findUnique: jest.fn(),
      update: jest.fn(),
      create: jest.fn(),
    },
  };

  //Create mock JwtService
  const mockJwtService = {
    sign: jest.fn(),
    verify: jest.fn(),
  };

  const mockConfigService = {
    get: jest.fn(),
  };

  // =====================SETUP BEFORE EACH TEST====================
  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AuthService,
        {
          provide: PrismaService,
          useValue: mockPrismaService,
        },
        {
          provide: JwtService,
          useValue: mockJwtService,
        },
        {
          provide: ConfigService,
          useValue: mockConfigService,
        },
      ],
    }).compile();

    service = module.get<AuthService>(AuthService);
  });

  // ===================CLEANUP AFTER EACH TEST===================
  afterEach(() => {
    jest.clearAllMocks();
  });

  // ==================== BASIC EXISTENCE TEST ====================
  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  // ==================== NESTED TEST SUITE FOR create() METHOD ====================
  describe('create() method', () => {
    const createDto: CreateAuthDto = {
      email: 'test@example.com',
      password: 'password123',
      name: 'Test User',
      phone: '1234567890',
      role: UserRole.MEMBER,
    };

    beforeEach(() => {
      jest.clearAllMocks();
    });

    // ==================== TEST 1: SUCCESSFUL USER CREATION ====================
    it('should create a new user successfully', async () => {
      // ARRANGE PHASE: Setup all mocks and test data
      // 1. Mock that no user exists with this email
      mockPrismaService.user.findUnique.mockResolvedValue(null);

      // 2. Mock bcrypt.hash
      (bcrypt.hash as jest.Mock).mockResolvedValue('hashed_password');

      // 3. Create mock user data that the service should return
      const mockUser = {
        id: 'uuid-123',
        memberId: '123456',
        email: 'test@example.com',
        name: 'Test User',
        profilePhoto: null,
        phone: '1234567890',
        role: UserRole.MEMBER,
        status: UserStatus.ACTIVE,
        createdAt: new Date(),
      };
      mockPrismaService.user.create.mockResolvedValue(mockUser);

      // Define the exact select object from your service
      const expectedSelect = {
        id: true,
        memberId: true,
        email: true,
        name: true,
        profilePhoto: true,
        phone: true,
        role: true,
        status: true,
        createdAt: true,
      };

      // ACT PHASE: Execute the method we're testing
      const result = await service.create(createDto);

      // ASSERT: Verify results
      expect(mockPrismaService.user.findUnique).toHaveBeenCalledWith({
        where: { email: 'test@example.com' },
      });

      expect(bcrypt.hash).toHaveBeenCalledWith('password123', 10);

      // Check if user.create was called with correct data
      expect(mockPrismaService.user.create).toHaveBeenCalledWith({
        data: {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
          memberId: expect.any(String), // Generated by generateUniqueMemberId()
          email: 'test@example.com',
          password: 'hashed_password',
          // Note: name and phone are NOT in the create data, only in select
        },
        select: expectedSelect,
      });

      // Check the returned result
      expect(result).toEqual(mockUser);
    });

    it('should throw ConflictException when user already exists and is ACTIVE', async () => {
      // ARRANGE
      const existingUser = {
        id: 'uuid-123',
        email: 'test@example.com',
        status: UserStatus.ACTIVE,
      };
      mockPrismaService.user.findUnique.mockResolvedValue(existingUser);

      // ACT & ASSERT
      await expect(service.create(createDto)).rejects.toThrow(
        ConflictException,
      );
      await expect(service.create(createDto)).rejects.toThrow(
        'User with this email already exist',
      );

      // ASSERT PHASE: Verify everything happened correctly

      //Assertion 1: Verify findUnique was called with correct email

      // Verify create was NOT called
      expect(mockPrismaService.user.create).not.toHaveBeenCalled();
    });

    it('should reactivate DELETED user', async () => {
      // ARRANGE
      const deletedUser = {
        id: 'uuid-123',
        email: 'test@example.com',
        status: UserStatus.DELETED,
      };

      const updatedUser = {
        ...deletedUser,
        status: UserStatus.ACTIVE,
        name: 'Test User',
        phone: '1234567890',
        role: UserRole.MEMBER,
      };

      mockPrismaService.user.findUnique.mockResolvedValue(deletedUser);
      (bcrypt.hash as jest.Mock).mockResolvedValue('hashed_password');
      mockPrismaService.user.update.mockResolvedValue(updatedUser);

      // ACT
      const result = await service.create(createDto);

      // ASSERT
      const { email, ...restOfDto } = createDto;
      expect(mockPrismaService.user.update).toHaveBeenCalledWith({
        where: { email: email },
        data: {
          ...restOfDto,
          password: 'hashed_password',
          status: UserStatus.ACTIVE,
        },
      });

      expect(mockPrismaService.user.create).not.toHaveBeenCalled();
      expect(result).toEqual(updatedUser);
    });
  });

  // ============================ Test 2: loginUser() method ====================
  describe('loginUser() method', () => {
    const loginDto: LoginAuthDto = {
      email: 'test@example.com',
      password: 'password123',
    };

    beforeEach(() => {
      jest.clearAllMocks();
    });

    it('should login successfully with valid credentials', async () => {
      // ARRANGE
      const mockUser = {
        id: 'uuid-123',
        email: 'test@example.com',
        password: 'hashed_password',
        role: UserRole.MEMBER,
        name: 'Test User',
      };

      mockPrismaService.user.findUnique.mockResolvedValue(mockUser);
      (bcrypt.compare as jest.Mock).mockResolvedValue(true);
      mockJwtService.sign
        .mockReturnValueOnce('access_token_123')
        .mockReturnValueOnce('refresh_token_456');
      mockConfigService.get.mockReturnValue('refresh_secret_key');

      // ACT
      const result = await service.loginUser(loginDto);

      // ASSERT
      expect(mockPrismaService.user.findUnique).toHaveBeenCalledWith({
        where: { email: 'test@example.com' },
      });

      expect(bcrypt.compare).toHaveBeenCalledWith(
        'password123',
        'hashed_password',
      );

      // Check first JWT sign call (access token)
      expect(mockJwtService.sign).toHaveBeenNthCalledWith(1, {
        sub: 'uuid-123',
        email: 'test@example.com',
        role: UserRole.MEMBER,
      });

      // Check second JWT sign call (refresh token)
      expect(mockJwtService.sign).toHaveBeenNthCalledWith(
        2,
        {
          sub: 'uuid-123',
          email: 'test@example.com',
          role: UserRole.MEMBER,
        },
        {
          secret: 'refresh_secret_key',
          expiresIn: '7d',
        },
      );

      expect(result).toEqual({
        accessToken: 'access_token_123',
        refreshToken: 'refresh_token_456',
        user: {
          id: 'uuid-123',
          email: 'test@example.com',
          role: UserRole.MEMBER,
          name: 'Test User',
        },
      });
    });

    it('should throw UnauthorizedException when user not found', async () => {
      // ARRANGE
      mockPrismaService.user.findUnique.mockResolvedValue(null);

      // ACT & ASSERT
      await expect(service.loginUser(loginDto)).rejects.toThrow(
        UnauthorizedException,
      );
      await expect(service.loginUser(loginDto)).rejects.toThrow(
        'Invalid Email or Password',
      );
    });

    it('should throw UnauthorizedException when password is invalid', async () => {
      // ARRANGE
      const mockUser = {
        id: 'uuid-123',
        email: 'test@example.com',
        password: 'hashed_password',
        role: UserRole.MEMBER,
        name: 'Test User',
      };

      mockPrismaService.user.findUnique.mockResolvedValue(mockUser);
      (bcrypt.compare as jest.Mock).mockResolvedValue(false);

      // ACT & ASSERT
      await expect(service.loginUser(loginDto)).rejects.toThrow(
        UnauthorizedException,
      );
      expect(bcrypt.compare).toHaveBeenCalledWith(
        'password123',
        'hashed_password',
      );
    });
  });

  // ============================ Test 3: refreshAccessToken() method ====================
  describe('refreshAccessToken() method', () => {
    const validRefreshToken = 'valid.refresh.token';
    const invalidRefreshToken = 'invalid.token';

    const mockJwtPayload = {
      sub: 'user-123',
      email: 'test@example.com',
      role: UserRole.MEMBER,
    };

    beforeEach(() => {
      jest.clearAllMocks();
    });

    it('should return new access token for valid refresh token', async () => {
      // ARRANGE
      mockJwtService.verify.mockResolvedValue(mockJwtPayload);
      mockConfigService.get.mockReturnValue('refresh_secret_key');
      mockJwtService.sign.mockReturnValue('new_access_token_123');

      // ACT
      const result = await service.refreshAccessToken(validRefreshToken);

      // ASSERT
      expect(mockJwtService.verify).toHaveBeenCalledWith(validRefreshToken, {
        secret: 'refresh_secret_key',
      });

      expect(mockJwtService.sign).toHaveBeenCalledWith({
        sub: 'user-123',
        email: 'test@example.com',
        role: UserRole.MEMBER,
      });

      expect(result).toEqual({
        accessToken: 'new_access_token_123',
      });
    });

    it('should throw UnauthorizedException for invalid refresh token', async () => {
      // ARRANGE
      mockJwtService.verify.mockRejectedValue(new Error('Token invalid'));

      // ACT & ASSERT
      await expect(
        service.refreshAccessToken(invalidRefreshToken),
      ).rejects.toThrow(UnauthorizedException);
    });

    it('should throw UnauthorizedException when refresh token is empty', async () => {
      // ACT & ASSERT
      await expect(service.refreshAccessToken('')).rejects.toThrow(
        UnauthorizedException,
      );
      await expect(service.refreshAccessToken('')).rejects.toThrow(
        'Refresh token is missing',
      );
    });
  });
});
